import java.util.HashMap;
import java.util.HashSet;

/**
 * Created by qihuiyang on 4/1/17.
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindTheDifference {
    public static char getFindTheDifference(String s, String t){

        int charCodeS = 0, charCodeT = 0;
        // Iterate through both strings and char codes
        for (int i = 0; i < s.length(); ++i){
            charCodeS += (int)s.charAt(i);
        }
        for (int i = 0; i < t.length(); ++i){
            charCodeT += (int)t.charAt(i);
        }
        // Return the difference
        return (char)(charCodeT - charCodeS);

    }
    public static void main(String[] args){
        String s = "abcd";
        String t = "abcde";

        Character res = getFindTheDifference(s,t);

        System.out.print("result is:" + res);

    }

}
